### ISSUE TITLE
[Bug]: Problems loading big graphs 

### ISSUE THREAD

**Issue by EdwinHernandezG** [JacobBumgarner/VesselVio#44]
### What happened?

Hi Jacob.

I was trying the new version of VesselVio and found that if I analyze several files in batch, everything goes right, and all the files are processed; however, when I try to visualize, the program stops at 70% in the creating mesh step. So it is not possible to visualize them. However, if I visualize them one by one, there is no issue, and the mesh is generated.

Also, one general question is if the skeleton and vessel radii are analyzed with the visualize option, is there a way to export the graph and the features table?.

Again, thanks in advance for your help.

### Operating System

Windows

### App Build

Downloaded App

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JacobBumgarner** [comment]
Thanks for reaching out!

So I'm going to address this one in two parts:

**1. 'Stuck' at 70%':**
What this likely means is that your computer has run out of memory. Once the progress bar hits 70%, this means that the dataset has been completely analyzed, and that the mesh being is constructed. I'm assuming you're trying to visualize a large dataset?

**2. Export results from visualization**
This is a great suggestion, and I really like the idea. Would you mind opening this up as a [Feature Request] rather than a bug?

I'm going to go ahead and close this issue, as there is no obvious bug here.

**Comment by EdwinHernandezG** [comment]
Sorry to open this again; I don't think it is a memory issue.

In the snapshot, you can see that the process stopped at 70%

![image](https://user-images.githubusercontent.com/61184296/171583917-c17c0b75-6050-4a98-9bbc-30c8a84b689a.png)

But almost no resources are used in the workstation:

![image](https://user-images.githubusercontent.com/61184296/171584208-fcceea64-7e99-415f-8a3d-2a91eb667db7.png)

And, as I said before, if I visualize the skeleton directly, there is no issue, it takes a little bit of time, but I get the skeleton visualized. So I think there is an issue loading the graph file.

![image](https://user-images.githubusercontent.com/61184296/171595907-017ffbbf-b1da-493b-a609-55b018ca56aa.png)

I can send you the graph file.

Thanks again.

Edwin
